import React from 'react';

interface TermsOfServiceProps {
  onBack: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-background-light dark:bg-background-dark py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-primary mb-8 hover:underline"
        >
          <span className="material-symbols-outlined">arrow_back</span>
          Back to Home
        </button>
        
        <h1 className="font-headline text-4xl font-bold text-text-primary-light dark:text-text-primary-dark mb-8">
          Terms of Service
        </h1>
        
        <div className="prose prose-lg max-w-none text-text-primary-light/80 dark:text-text-primary-dark/80 space-y-6">
          <p className="text-sm text-text-primary-light/60">Last updated: December 1, 2024</p>
          
          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Mehndi Design ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">2. Description of Service</h2>
            <p>
              Mehndi Design provides an AI-powered platform for generating custom henna/mehndi designs based on 
              user-uploaded hand photographs. We also offer booking services for professional mehndi artists.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">3. User Accounts</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You must provide accurate and complete information when creating an account</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must be at least 13 years old to use this Service</li>
              <li>One person may not maintain more than one account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">4. AI-Generated Designs</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Designs generated by our AI are for personal use</li>
              <li>You may use generated designs for your own mehndi application</li>
              <li>Commercial redistribution of AI-generated designs is prohibited</li>
              <li>We do not guarantee that AI designs will be unique or original</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">5. Booking Services</h2>
            <h3 className="text-xl font-semibold mt-4 mb-2">Artist Booking Terms</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Bookings are subject to artist availability</li>
              <li>Service area: Greater Noida and surrounding areas</li>
              <li>Pricing: ₹100 per hand (subject to change)</li>
              <li>Available days: Sunday and Monday</li>
              <li>Cancellations must be made at least 24 hours in advance</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">6. User Content</h2>
            <p>
              By uploading photographs to our Service, you grant us a non-exclusive license to use these images 
              for the purpose of generating mehndi designs. You retain ownership of your original photographs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">7. Prohibited Uses</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Uploading inappropriate or offensive content</li>
              <li>Attempting to reverse-engineer our AI system</li>
              <li>Using the Service for any illegal purpose</li>
              <li>Harassing or impersonating other users</li>
              <li>Automated scraping or data collection</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">8. Limitation of Liability</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. We are not liable for any damages 
              arising from your use of the Service, including but not limited to allergic reactions to henna 
              products applied by third-party artists.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">9. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the Service after changes 
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary-light dark:text-text-primary-dark mt-8 mb-4">10. Contact</h2>
            <p>For questions about these Terms, contact us:</p>
            <ul className="list-none pl-0 mt-4 space-y-2">
              <li><strong>Email:</strong> himanshiparashar44@gmail.com</li>
              <li><strong>Phone/WhatsApp:</strong> +91 7011489500</li>
              <li><strong>Address:</strong> Greater Noida, Uttar Pradesh, India</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
